tutorial_photo_album/config/routes.rb
Rails.application.routes.draw do
  resources :photos
  root "photos#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

tutorial_photo_album/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

tutorial_photo_album/app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :file_location, PhotoImageUploader 
  validates_presence_of :title, :date, :description, :file_location
end

tutorial_photo_album/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

tutorial_photo_album/app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    if  @photo.save
      redirect_to photos_url
    else
      render :new
    end
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update_attributes(photo_params)
      redirect_to photo_path(@photo)
    else
      render :edit
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to photos_url
  end

  private

  def photo_params
    params.require(:photo).permit(:title, :date, :description, :file_location )
  end

end

tutorial_photo_album/app/helpers/application_helper.rb
module ApplicationHelper
end

tutorial_photo_album/app/helpers/photos_helper.rb
module PhotosHelper
end

tutorial_photo_album/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewPhotoAlbum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

tutorial_photo_album/app/views/photos/_form.html.erb
<% if @photo.errors.present?%>
  <ul>
    <% @photo.errors.each do |error, message|%>
      <li> <%= "#{error.capitalize}  #{message}" %></li>
    <% end %>
  </ul>
<% end%>
<div class="form container">
<%= form_for @photo do |f| %>

  <div class="form-group">
    <%= f.label :title%>
    <%= f.text_field :title, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :date%>
    <%= f.text_field :date, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :description%>
    <%= f.text_field :description, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :file_location%>
    <%= f.file_field :file_location%>
  </div>

  <%= f.submit %>

<% end %>
</div>

tutorial_photo_album/app/views/photos/edit.html.erb
<%= render :partial => "form" %>

tutorial_photo_album/app/views/photos/index.html.erb
<table class="table table-striped table-condensed">
  <% @photos.each do |photo| %>
    <tr>
      <td><%= photo.title %></td>
      <td><%= link_to "Show", photo_path(photo) %></td>
      <td><%= link_to "Edit", edit_photo_path(photo) %></td>
      <td><%= link_to "Destroy", photo_path(photo), method: :delete, data:{confirm: "Are you sure?"} %></td>
    </tr>
  <% end %>
</table>
<%= link_to "New photo", new_photo_path %>

tutorial_photo_album/app/views/photos/new.html.erb
<%= render :partial => "form" %>

tutorial_photo_album/app/views/photos/show.html.erb
<%= @photo.title%>
<%= @photo.date%>
<%= image_tag @photo.file_location.url, size: "140x140",class: "img-thumbnail" %>
<%= @photo.description %>
<p>
<%= link_to "Back to index", photos_path %>
</p>