config/routes.rb
Rails.application.routes.draw do
  resources :todos
  root "todos#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end
  def new
    @todo = Todo.new
  end
  def create
   @todo = Todo.new(todo_params)
   @todo.save

   redirect_to todos_url
  end
  def edit
    @todo = Todo.find(params[:id])
  end
  def update
    @todo = Todo.find(params[:id])
    @todo.update_attributes(todo_params)

    redirect_to todos_url
  end
  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy

    redirect_to todos_url
  end

  private

  def todo_params
   params.require(:todo).permit(:input, :done)
  end
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/edit.html.erb
<tr>
<%= form_for @todo do |f| %>
   <%= f.label :input, "To do" %>
   <%= f.text_field :input %>

   <%= f.label :done, "Done" %>
   <%= f.text_field :done %>

   <%= f.submit "Update" %>
<% end %>
</tr>

app/views/todos/index.html.erb
<table>
  <tr>
    <th>Name</th>
    <th colspan="3">Done</th>
  </tr>
  <tr>
<% @todos.each do |todo| %>

    <td><%= todo.input %></td>
    <td><%= todo.done %></td>

    <td class = "link_to"><%= link_to 'Edit', edit_todo_path(todo) %></td>
    <td class = "link_to"><%= link_to 'Delete', todo_path(todo), method: :delete, data:{ confirm: "Are you sure?" } %></td>

  </tr>
<% end %>
  <tr>
    <td colspan="4" class = "link_to" class="new"><%= link_to 'New To Do', new_todo_path %></td>
  <tr>
</table>

app/views/todos/new.html.erb
<tr>
<%= form_for @todo, :url => todos_path do |f| %>
   <%= f.label :input, "To do" %>
   <%= f.text_field :input %>

   <%= f.label :done, "Done" %>
   <%= f.text_field :done %>


   <%= f.submit "Create" %>
<% end %>
</tr>